version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: kafka-docker
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      #KAFKA_ADVERTISED_HOST_NAME: kafkasrc.localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Topic1:1:1,Topic2:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
